RUD Customer include: index, edit, route, controller
alexzvn/shale-pizza pull request #14
Opened 2022-04-18 15:54 UTC by QuanIce

2022-04-18 16:03 UTC, alexzvn requested changes

2022-04-18 16:03 UTC, alexzvn commented on app/Http/Controllers/Dashboard/CustomerController.php
> +        $attributes = $this->validate($request, [
Chưa tái sử dụng method rules()

2022-04-18 16:03 UTC, alexzvn commented on app/Http/Controllers/Dashboard/CustomerController.php
> +        return [
Các rule validate chưa chặt chẽ

2022-04-18 16:03 UTC, alexzvn commented on resources/views/dashboard/customer/edit.blade.php
> +                @include('components.input', [
thiếu type = email

2022-04-18 16:03 UTC, alexzvn commented on resources/views/dashboard/customer/edit.blade.php
> +                    'value' => $customer->email
Thiếu type = email

2022-04-18 16:03 UTC, alexzvn commented on resources/views/dashboard/customer/edit.blade.php
> +                @include('components.input', [
Gender select phải là dạng select/options

2022-04-18 16:31 UTC, QuanIce commented on resources/views/dashboard/customer/edit.blade.php
> +                @include('components.input', [
select option đã set nhưng không update được trong database, nhập "male" => update sang trang index ra số

2022-04-18 16:31 UTC, QuanIce commented on resources/views/dashboard/customer/edit.blade.php
> +                    'value' => $customer->email
Đã sửa

2022-04-18 16:38 UTC, QuanIce commented on app/Http/Controllers/Dashboard/CustomerController.php
> +        $attributes = $this->validate($request, [
Đã sửa

2022-04-18 16:43 UTC, QuanIce commented on app/Http/Controllers/Dashboard/CustomerController.php
> +        return [
đã sửa

2022-04-18 16:46 UTC, alexzvn commented on resources/views/dashboard/customer/edit.blade.php
> +                @include('components.input', [
Các option nên để value là số, nó được quy định trong file [app/Enums/Gender.php](https://github.com/alexzvn/shale-pizza/blob/main/app/Enums/Gender.php)

2022-04-19 07:56 UTC, alexzvn approved these changes
acceptable

2022-04-19 07:56 UTC, merged